version: "3.7"

networks: 
  ghost_net:
    driver: bridge

#### TODO: change the service names (ghost_XXX) if you want better naming, remember to match them in nginx config
services:
  ghost_one:
    networks: 
      - ghost_net
    image: ghost:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DATA_DIR/$FIRST_BLOG_NAME/content:/var/lib/ghost/content
    depends_on:
      - swag
    environment:
      - url=https://$FIRST_DOMAINNAME
      - server__host=0.0.0.0
      - server__port=2368
      - imageOptimization__resize=false
      - NODE_ENV=production   # TODO: use 'production' or 'development accordingly'

  ghost_two:
    networks: 
      - ghost_net
    image: ghost:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DATA_DIR/$SECOND_BLOG_NAME/content:/var/lib/ghost/content
    depends_on:
      - swag
    environment:
      - url=https://$SECOND_DOMAINNAME
      - server__host=0.0.0.0
      - server__port=2368
      - imageOptimization__resize=false
      - NODE_ENV=production   # TODO: use 'production' or 'development accordingly'


  swag:
    image: ghcr.io/linuxserver/swag
    restart: unless-stopped
    container_name: swag
    networks:
      - ghost_net
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # Cert domain info
      - URL=$FIRST_DOMAINNAME
      - SUBDOMAINS=www # optionally use 'wildcard' for a wildcard certificate
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS=$SECOND_DOMAINNAME   # if in need of secondary blog, untick this  
      # Cert validation and parameters
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=$CERT_POSTMASTER_MAIL
      - DHLEVEL=4096 # Default is 2048
      - STAGING=true # use staging to test config first
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - $CONFIG_DIR/swag/config:/config
      - ./cloudflare.ini:/config/dns-conf/cloudflare.ini:ro
      - $CONFIG_DIR/nginx/default:/config/nginx/site-confs/default
